server:
  port: 8763
user:
  userServiceUrl: http://127.0.0.1:8762/
spring:
  application:
    name: microservice-provider-movie

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
